package uz.pdp.appmilliytaomlarserver.bot;

public interface BotState {
    String CHOOSE_LANG = "CHOOSE_LANG";  // TIL TANLIDI
    String SHARE_CONTACT = "SHARE_CONTACT"; // CONTAKT JONATADI
    String SHARE_FIRST_NAME = "SHARE_FIRST_NAME"; //ISIM JONATADI
    String CHOOSE_CATEGORY = "CHOOSE_CATEGORY"; // MINU TANLIDI
    String CHOOSE_CHILDERN_CATEGORY = "CHOOSE_CATEGORY"; // MINU TANLIDI
    String CHOOSE_PRODUCT = "CHOOSE_PRODUCT"; // MAHSULOT TANLIDI
    String CHOOSE_PRODUCT_FOTO = "CHOOSE_PRODUCT"; // MAHSULOT TANLIDI
    String SHOUW_PRODUCT = "CHOOSE_PRODUCT"; // MAHSULOT TANLIDI
    String SHARE_ORDER_TYPE = "SHARE_ORDER_TYPE";// SABOY, OSHERDA, DASTAFKA
    String CHOOSE_AMOUNT = "CHOOSE_AMOUNT"; // MAXSULOT SONI
    String SHOUW_TAME = "CHOOSE_AMOUNT"; // SOAT
    String CHOOSE_TAME = "CHOOSE_AMOUNT"; // SOAT
    String SAVE_TAME = "CHOOSE_AMOUNT"; // SOAT
    String CHOOSE_LOCATION_OR_ADDRESS = "CHOOSE_LOCATION_OR_ADDRESS"; // MANZILI
    String SHOW_BASKET = "SHOW_BASKET"; // KARZINKA
    String CHOOSE_DATE= "CHOOSE_DATE"; // KUN TANLASH
    String FINISH_ORDER = "FINISH_ORDER"; //

}
